### Lec 01: Data Science Process
### Lec 02: What is EDA
### Lec 03: Introduction to pandas

In [1]:
import numpy as np
import pandas as pd

In [3]:
info = {
    "Name" : ["Sourabh","Harshita","Shraddha"],
    "CGPA" : [8.7,9.8,8.5]
}

df = pd.DataFrame(info)
print(df)

       Name  CGPA
0   Sourabh   8.7
1  Harshita   9.8
2  Shraddha   8.5

In [4]:
df

       Name  CGPA
0   Sourabh   8.7
1  Harshita   9.8
2  Shraddha   8.5

### Lec 04: Series => 1D labelled array
- First type of DataStructure in pandas is "Series"

In [10]:
# Define Series using py_list

s = pd.Series([1,2,3,4,5])
print(s)
print(type(s))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [11]:
# access element of series 
# first method using Index 

print(s[0])
print(s[4])

1
5

In [12]:
# but also we can assign index => lable value for series like

s = pd.Series([1,2,3,4,5],index = ["Sourabh","Mina","Raj","Jaya","Dhanashree"])
print(s)

Sourabh       1
Mina          2
Raj           3
Jaya          4
Dhanashree    5
dtype: int64

In [16]:
# now we can access series element using the labelled. 

print(s["Sourabh"])
print(s["Jaya"])

# also we can access element using index 
print(s[0]) # also for now just ignore the warning.

1
4
1

C:\Users\HP\AppData\Local\Temp\ipykernel_2764\1615829844.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0]) # also for now just ignore the warning.

### Lec 05: Series Properties

- Homogenous
- Vectorized Operations
- Handle Missing values with NaN
- Mutable values, immutable size

In [19]:
# Homogenous 
s = pd.Series([1,2,3,4,5,"xzy"],index = ["Sourabh","Mina","Raj","Jaya","Dhanashree",32])
print(s)
# Observe dtype of current series and above cell seires. here I can added "xzy" string into the seires
# then pandas change it's type into to object. Means it's Homogenous means store all types of data. 

# print(s["Sourabh"])

Sourabh         1
Mina            2
Raj             3
Jaya            4
Dhanashree      5
32            xzy
dtype: object
1

In [21]:
# Vectorized Operation 
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([10,20,30,40,50])

print(s1 + s2)

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [28]:
# Handle Missing values with NaN => Learn in upcoming Lecture

# Mutable values, immutable size

s1 = pd.Series([1,2,3,4,5])
 # Mutuable values 
s1[0] = 47
print(s1)

# but immutable in size means we want to drop or add a element in series we want to create another new series. 

s1.drop(0)
print(s1) # It's not working but following lines are working becuse of assign new changes in another variable.  

changed_s1 = s1.drop(0)
print(changed_s1)

0    47
1     2
2     3
3     4
4     5
dtype: int64
0    47
1     2
2     3
3     4
4     5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

### Lec 06 => 2D labelled array

In [32]:
# create DataFrame using Dictionary of list

info = {
    "Name" : ["Adam","Bob","Cad"],
    "Age" : [23,43,32],
    "GPA" : [9.9, 9.7, 8.7]
}

df = pd.DataFrame(info)
print(df, type(df))

print(df.index)
print(df.columns)

   Name  Age  GPA
0  Adam   23  9.9
1   Bob   43  9.7
2   Cad   32  8.7 <class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'GPA'], dtype='object')

In [36]:
# create DataFrame using List of list
df = pd.DataFrame([ ["adam",34], ["bob",32], ["Eve",32] ], columns=["name","age"])
print(df)

   name  age
0  adam   34
1   bob   32
2   Eve   32

In [ ]:
# create DataFrame using Numpy Array
np_arr = np.array([ [1,2,3], [4,5,6]]), columns=[]

### Lec 07: Pandas with csv & JSON data - give file.

In [8]:
# Read CSV file

df = pd.read_csv("employee_data.csv")
print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [9]:
# Read JSON file
df = pd.read_json("employee.json")
print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

### Lec 08: DataFrame Methods

In [10]:
df = pd.read_csv("employee_data.csv")
print(df)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [11]:
# Data Frame Methods

df.head() # by default give us 5 rows of the table but also set explicit value for printing table.

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [12]:
df.head(7) # set explicit value.

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000

In [13]:
df.tail() # print last 5 rows by default but we can set explicit value

   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [14]:
df.tail(7)

   ID    Name  Age Department  Salary
3   4   David   45  Marketing   91000
4   5     Eva   38         IT   65000
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [15]:
df.sample() # It's give us sample row in a table. every time givs us different table.

   ID   Name  Age Department  Salary
5   6  Frank   29    Finance   50000

In [17]:
df.info() # It give us sample information about the table. read following table.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

In [20]:
df.shape # It give us exact shape of table.

(10, 5)

In [22]:
df.describe() # It describe about the table columns and give some useful information.

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [24]:
df.columns # it give us column name of table

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')

In [27]:
df.nunique() # It give us unique value in columns.

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64